<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Tests\Controllers;

use TaamAiUserLib\Controllers\ChatWithPdfController;
use TaamAiUserLib\Exceptions;

class ChatWithPdfControllerTest extends BaseTestController
{
    /**
     * @var ChatWithPdfController ChatWithPdfController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getChatWithPdfController();
    }

    public function testSendAndGetMsgToChatPdf()
    {
        // Parameters for the API call
        $question = 'what is the education';

        // Perform API call
        try {
            self::$controller->sendAndGetMsgToChatPdf($question);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testAnswerTheQuestion()
    {
        // Perform API call
        try {
            self::$controller->answerTheQuestion();
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testNewRequest()
    {
        // Parameters for the API call
        $question = 'what data this file contains';
        $path = 'assets/pdf/64ef458eabc4e_Soban-Shahid (Laravel).pdf';

        // Perform API call
        try {
            self::$controller->newRequest($question, $path);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
