<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Tests\Controllers;

use TaamAiUserLib\Controllers\MiscController;
use TaamAiUserLib\Exceptions;

class MiscControllerTest extends BaseTestController
{
    /**
     * @var MiscController MiscController instance
     */
    protected static $controller;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$controller = parent::getClient()->getMiscController();
    }

    public function testAllCategories()
    {
        // Parameters for the API call
        $userId = 40;

        // Perform API call
        try {
            self::$controller->allCategories($userId);
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }

    public function testNewRequest()
    {
        // Perform API call
        try {
            self::$controller->newRequest();
        } catch (Exceptions\ApiException $e) {
        }

        // Assert result with expected response
        $this->newTestCase(null)->expectStatus(200)->assert();
    }
}
