<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\AddAndRemoveFromFavDocument;

/**
 * Builder for model AddAndRemoveFromFavDocument
 *
 * @see AddAndRemoveFromFavDocument
 */
class AddAndRemoveFromFavDocumentBuilder
{
    /**
     * @var AddAndRemoveFromFavDocument
     */
    private $instance;

    private function __construct(AddAndRemoveFromFavDocument $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new add and remove from fav document Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new AddAndRemoveFromFavDocument($status, $message));
    }

    /**
     * Initializes a new add and remove from fav document object.
     */
    public function build(): AddAndRemoveFromFavDocument
    {
        return CoreHelper::clone($this->instance);
    }
}
