<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\AllWorkbooksLive;

/**
 * Builder for model AllWorkbooksLive
 *
 * @see AllWorkbooksLive
 */
class AllWorkbooksLiveBuilder
{
    /**
     * @var AllWorkbooksLive
     */
    private $instance;

    private function __construct(AllWorkbooksLive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new all workbooks live Builder object.
     */
    public static function init(int $code, string $status, string $mesaage, array $data): self
    {
        return new self(new AllWorkbooksLive($code, $status, $mesaage, $data));
    }

    /**
     * Initializes a new all workbooks live object.
     */
    public function build(): AllWorkbooksLive
    {
        return CoreHelper::clone($this->instance);
    }
}
