<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\ContentsInWorkBook;

/**
 * Builder for model ContentsInWorkBook
 *
 * @see ContentsInWorkBook
 */
class ContentsInWorkBookBuilder
{
    /**
     * @var ContentsInWorkBook
     */
    private $instance;

    private function __construct(ContentsInWorkBook $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new contents in work book Builder object.
     */
    public static function init(string $status, string $message, int $count, array $data): self
    {
        return new self(new ContentsInWorkBook($status, $message, $count, $data));
    }

    /**
     * Initializes a new contents in work book object.
     */
    public function build(): ContentsInWorkBook
    {
        return CoreHelper::clone($this->instance);
    }
}
