<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\CreateProduct;

/**
 * Builder for model CreateProduct
 *
 * @see CreateProduct
 */
class CreateProductBuilder
{
    /**
     * @var CreateProduct
     */
    private $instance;

    private function __construct(CreateProduct $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create product Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new CreateProduct($status, $message));
    }

    /**
     * Initializes a new create product object.
     */
    public function build(): CreateProduct
    {
        return CoreHelper::clone($this->instance);
    }
}
