<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\CreateFolderLive;
use TaamAiUserLib\Models\Data3;

/**
 * Builder for model CreateFolderLive
 *
 * @see CreateFolderLive
 */
class CreateFolderLiveBuilder
{
    /**
     * @var CreateFolderLive
     */
    private $instance;

    private function __construct(CreateFolderLive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create folder live Builder object.
     */
    public static function init(string $status, string $message, Data3 $data): self
    {
        return new self(new CreateFolderLive($status, $message, $data));
    }

    /**
     * Initializes a new create folder live object.
     */
    public function build(): CreateFolderLive
    {
        return CoreHelper::clone($this->instance);
    }
}
