<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\CreatePromptTemplate;

/**
 * Builder for model CreatePromptTemplate
 *
 * @see CreatePromptTemplate
 */
class CreatePromptTemplateBuilder
{
    /**
     * @var CreatePromptTemplate
     */
    private $instance;

    private function __construct(CreatePromptTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create prompt template Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new CreatePromptTemplate($status, $message));
    }

    /**
     * Initializes a new create prompt template object.
     */
    public function build(): CreatePromptTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
