<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\CreateCustomTemplate;
use TaamAiUserLib\Models\Data12;

/**
 * Builder for model CreateCustomTemplate
 *
 * @see CreateCustomTemplate
 */
class CreateCustomTemplateBuilder
{
    /**
     * @var CreateCustomTemplate
     */
    private $instance;

    private function __construct(CreateCustomTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create custom template Builder object.
     */
    public static function init(string $code, string $status, string $message, Data12 $data): self
    {
        return new self(new CreateCustomTemplate($code, $status, $message, $data));
    }

    /**
     * Initializes a new create custom template object.
     */
    public function build(): CreateCustomTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
