<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data1;

/**
 * Builder for model Data1
 *
 * @see Data1
 */
class Data1Builder
{
    /**
     * @var Data1
     */
    private $instance;

    private function __construct(Data1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 1 Builder object.
     */
    public static function init(
        int $id,
        int $userId,
        string $name,
        int $default,
        string $createdAt,
        string $updatedAt,
        array $folders
    ): self {
        return new self(new Data1($id, $userId, $name, $default, $createdAt, $updatedAt, $folders));
    }

    /**
     * Sets deleted at field.
     */
    public function deletedAt(?string $value): self
    {
        $this->instance->setDeletedAt($value);
        return $this;
    }

    /**
     * Initializes a new data 1 object.
     */
    public function build(): Data1
    {
        return CoreHelper::clone($this->instance);
    }
}
