<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data14;

/**
 * Builder for model Data14
 *
 * @see Data14
 */
class Data14Builder
{
    /**
     * @var Data14
     */
    private $instance;

    private function __construct(Data14 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 14 Builder object.
     */
    public static function init(
        int $id,
        int $userId,
        string $name,
        string $description,
        string $featureImage,
        string $bulletPoints,
        string $targetAudience,
        string $tags,
        string $deletedAt
    ): self {
        return new self(new Data14(
            $id,
            $userId,
            $name,
            $description,
            $featureImage,
            $bulletPoints,
            $targetAudience,
            $tags,
            $deletedAt
        ));
    }

    /**
     * Initializes a new data 14 object.
     */
    public function build(): Data14
    {
        return CoreHelper::clone($this->instance);
    }
}
