<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data9;

/**
 * Builder for model Data9
 *
 * @see Data9
 */
class Data9Builder
{
    /**
     * @var Data9
     */
    private $instance;

    private function __construct(Data9 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 9 Builder object.
     */
    public static function init(
        int $id,
        int $userId,
        string $model,
        string $title,
        string $instructions,
        string $code,
        int $workbookId,
        int $workbookFolderId,
        string $createdAt,
        string $updatedAt
    ): self {
        return new self(new Data9(
            $id,
            $userId,
            $model,
            $title,
            $instructions,
            $code,
            $workbookId,
            $workbookFolderId,
            $createdAt,
            $updatedAt
        ));
    }

    /**
     * Sets deleted at field.
     */
    public function deletedAt(?string $value): self
    {
        $this->instance->setDeletedAt($value);
        return $this;
    }

    /**
     * Initializes a new data 9 object.
     */
    public function build(): Data9
    {
        return CoreHelper::clone($this->instance);
    }
}
