<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data10;

/**
 * Builder for model Data10
 *
 * @see Data10
 */
class Data10Builder
{
    /**
     * @var Data10
     */
    private $instance;

    private function __construct(Data10 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 10 Builder object.
     */
    public static function init(
        int $id,
        string $name,
        string $subName,
        string $chatCode,
        string $logo,
        int $status,
        string $prompt,
        string $description,
        string $category,
        string $type,
        string $createdAt,
        string $updatedAt
    ): self {
        return new self(new Data10(
            $id,
            $name,
            $subName,
            $chatCode,
            $logo,
            $status,
            $prompt,
            $description,
            $category,
            $type,
            $createdAt,
            $updatedAt
        ));
    }

    /**
     * Sets deleted at field.
     */
    public function deletedAt(?string $value): self
    {
        $this->instance->setDeletedAt($value);
        return $this;
    }

    /**
     * Initializes a new data 10 object.
     */
    public function build(): Data10
    {
        return CoreHelper::clone($this->instance);
    }
}
