<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data17;

/**
 * Builder for model Data17
 *
 * @see Data17
 */
class Data17Builder
{
    /**
     * @var Data17
     */
    private $instance;

    private function __construct(Data17 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 17 Builder object.
     */
    public static function init(
        int $userId,
        string $name,
        string $description,
        string $resolution,
        string $image,
        string $planType,
        string $storage,
        string $expiresAt,
        string $imageName,
        string $workbookId,
        string $workbookFolderId,
        string $updatedAt,
        string $createdAt,
        int $id,
        string $imageUrl
    ): self {
        return new self(new Data17(
            $userId,
            $name,
            $description,
            $resolution,
            $image,
            $planType,
            $storage,
            $expiresAt,
            $imageName,
            $workbookId,
            $workbookFolderId,
            $updatedAt,
            $createdAt,
            $id,
            $imageUrl
        ));
    }

    /**
     * Initializes a new data 17 object.
     */
    public function build(): Data17
    {
        return CoreHelper::clone($this->instance);
    }
}
