<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data6;

/**
 * Builder for model Data6
 *
 * @see Data6
 */
class Data6Builder
{
    /**
     * @var Data6
     */
    private $instance;

    private function __construct(Data6 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 6 Builder object.
     */
    public static function init(
        int $id,
        int $userId,
        string $language,
        string $languageFlag,
        string $voice,
        string $voiceId,
        string $gender,
        string $text,
        int $workbookId,
        int $workbookFolderId,
        string $textRaw,
        string $fileName,
        string $resultUrl,
        string $resultExt,
        string $storage,
        string $title,
        string $vendor,
        string $vendorId,
        int $characters,
        string $voiceType,
        string $planType,
        string $audioType,
        string $mode,
        string $createdAt,
        string $updatedAt
    ): self {
        return new self(new Data6(
            $id,
            $userId,
            $language,
            $languageFlag,
            $voice,
            $voiceId,
            $gender,
            $text,
            $workbookId,
            $workbookFolderId,
            $textRaw,
            $fileName,
            $resultUrl,
            $resultExt,
            $storage,
            $title,
            $vendor,
            $vendorId,
            $characters,
            $voiceType,
            $planType,
            $audioType,
            $mode,
            $createdAt,
            $updatedAt
        ));
    }

    /**
     * Sets project field.
     */
    public function project(?string $value): self
    {
        $this->instance->setProject($value);
        return $this;
    }

    /**
     * Sets expires at field.
     */
    public function expiresAt(?string $value): self
    {
        $this->instance->setExpiresAt($value);
        return $this;
    }

    /**
     * Sets deleted at field.
     */
    public function deletedAt(?string $value): self
    {
        $this->instance->setDeletedAt($value);
        return $this;
    }

    /**
     * Initializes a new data 6 object.
     */
    public function build(): Data6
    {
        return CoreHelper::clone($this->instance);
    }
}
