<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data3;

/**
 * Builder for model Data3
 *
 * @see Data3
 */
class Data3Builder
{
    /**
     * @var Data3
     */
    private $instance;

    private function __construct(Data3 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 3 Builder object.
     */
    public static function init(
        string $name,
        string $workbookId,
        string $userId,
        string $icon,
        string $updatedAt,
        string $createdAt,
        int $id
    ): self {
        return new self(new Data3($name, $workbookId, $userId, $icon, $updatedAt, $createdAt, $id));
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new data 3 object.
     */
    public function build(): Data3
    {
        return CoreHelper::clone($this->instance);
    }
}
