<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data8;

/**
 * Builder for model Data8
 *
 * @see Data8
 */
class Data8Builder
{
    /**
     * @var Data8
     */
    private $instance;

    private function __construct(Data8 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 8 Builder object.
     */
    public static function init(
        int $id,
        int $userId,
        string $name,
        string $description,
        string $image,
        int $workbookId,
        int $workbookFolderId,
        string $storage,
        string $imageName,
        string $resolution,
        string $planType,
        string $expiresAt,
        string $createdAt,
        string $updatedAt
    ): self {
        return new self(new Data8(
            $id,
            $userId,
            $name,
            $description,
            $image,
            $workbookId,
            $workbookFolderId,
            $storage,
            $imageName,
            $resolution,
            $planType,
            $expiresAt,
            $createdAt,
            $updatedAt
        ));
    }

    /**
     * Sets deleted at field.
     */
    public function deletedAt(?string $value): self
    {
        $this->instance->setDeletedAt($value);
        return $this;
    }

    /**
     * Initializes a new data 8 object.
     */
    public function build(): Data8
    {
        return CoreHelper::clone($this->instance);
    }
}
