<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data13;

/**
 * Builder for model Data13
 *
 * @see Data13
 */
class Data13Builder
{
    /**
     * @var Data13
     */
    private $instance;

    private function __construct(Data13 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 13 Builder object.
     */
    public static function init(
        int $id,
        int $userId,
        string $name,
        string $description,
        string $bulletPoints,
        string $targetAudience
    ): self {
        return new self(new Data13($id, $userId, $name, $description, $bulletPoints, $targetAudience));
    }

    /**
     * Sets feature image field.
     */
    public function featureImage(?string $value): self
    {
        $this->instance->setFeatureImage($value);
        return $this;
    }

    /**
     * Sets tags field.
     */
    public function tags(?string $value): self
    {
        $this->instance->setTags($value);
        return $this;
    }

    /**
     * Sets deleted at field.
     */
    public function deletedAt(?string $value): self
    {
        $this->instance->setDeletedAt($value);
        return $this;
    }

    /**
     * Initializes a new data 13 object.
     */
    public function build(): Data13
    {
        return CoreHelper::clone($this->instance);
    }
}
