<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data11;

/**
 * Builder for model Data11
 *
 * @see Data11
 */
class Data11Builder
{
    /**
     * @var Data11
     */
    private $instance;

    private function __construct(Data11 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 11 Builder object.
     */
    public static function init(
        int $id,
        string $createdAt,
        string $updatedAt,
        string $alias,
        string $name,
        string $type,
        string $lang,
        string $content,
        string $response,
        int $userId,
        int $paid,
        int $ai,
        int $aiDone,
        int $aiUsedTokens,
        int $active,
        int $price,
        string $md
    ): self {
        return new self(new Data11(
            $id,
            $createdAt,
            $updatedAt,
            $alias,
            $name,
            $type,
            $lang,
            $content,
            $response,
            $userId,
            $paid,
            $ai,
            $aiDone,
            $aiUsedTokens,
            $active,
            $price,
            $md
        ));
    }

    /**
     * Sets deleted at field.
     */
    public function deletedAt(?string $value): self
    {
        $this->instance->setDeletedAt($value);
        return $this;
    }

    /**
     * Initializes a new data 11 object.
     */
    public function build(): Data11
    {
        return CoreHelper::clone($this->instance);
    }
}
