<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data7;

/**
 * Builder for model Data7
 *
 * @see Data7
 */
class Data7Builder
{
    /**
     * @var Data7
     */
    private $instance;

    private function __construct(Data7 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 7 Builder object.
     */
    public static function init(
        int $id,
        int $userId,
        string $url,
        string $transcript,
        int $workbookId,
        int $workbookFolderId,
        string $title,
        string $workbook,
        string $task,
        int $words,
        string $format,
        string $audioType,
        string $storage,
        string $length,
        string $planType,
        string $size,
        string $fileName,
        string $tempName,
        string $expiresAt,
        string $createdAt,
        string $updatedAt
    ): self {
        return new self(new Data7(
            $id,
            $userId,
            $url,
            $transcript,
            $workbookId,
            $workbookFolderId,
            $title,
            $workbook,
            $task,
            $words,
            $format,
            $audioType,
            $storage,
            $length,
            $planType,
            $size,
            $fileName,
            $tempName,
            $expiresAt,
            $createdAt,
            $updatedAt
        ));
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets deleted at field.
     */
    public function deletedAt(?string $value): self
    {
        $this->instance->setDeletedAt($value);
        return $this;
    }

    /**
     * Initializes a new data 7 object.
     */
    public function build(): Data7
    {
        return CoreHelper::clone($this->instance);
    }
}
