<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data5;

/**
 * Builder for model Data5
 *
 * @see Data5
 */
class Data5Builder
{
    /**
     * @var Data5
     */
    private $instance;

    private function __construct(Data5 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new data 5 Builder object.
     */
    public static function init(
        int $id,
        string $name,
        string $icon,
        int $workbookId,
        int $userId,
        int $status,
        string $createdAt,
        string $updatedAt,
        string $deletedAt
    ): self {
        return new self(
            new Data5($id, $name, $icon, $workbookId, $userId, $status, $createdAt, $updatedAt, $deletedAt)
        );
    }

    /**
     * Sets description field.
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Initializes a new data 5 object.
     */
    public function build(): Data5
    {
        return CoreHelper::clone($this->instance);
    }
}
