<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\DeleteAllKindOfDocuments;

/**
 * Builder for model DeleteAllKindOfDocuments
 *
 * @see DeleteAllKindOfDocuments
 */
class DeleteAllKindOfDocumentsBuilder
{
    /**
     * @var DeleteAllKindOfDocuments
     */
    private $instance;

    private function __construct(DeleteAllKindOfDocuments $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new delete all kind of documents Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new DeleteAllKindOfDocuments($status, $message));
    }

    /**
     * Initializes a new delete all kind of documents object.
     */
    public function build(): DeleteAllKindOfDocuments
    {
        return CoreHelper::clone($this->instance);
    }
}
