<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\DeleteProduct;

/**
 * Builder for model DeleteProduct
 *
 * @see DeleteProduct
 */
class DeleteProductBuilder
{
    /**
     * @var DeleteProduct
     */
    private $instance;

    private function __construct(DeleteProduct $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new delete product Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new DeleteProduct($status, $message));
    }

    /**
     * Initializes a new delete product object.
     */
    public function build(): DeleteProduct
    {
        return CoreHelper::clone($this->instance);
    }
}
