<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\DeleteFolder;

/**
 * Builder for model DeleteFolder
 *
 * @see DeleteFolder
 */
class DeleteFolderBuilder
{
    /**
     * @var DeleteFolder
     */
    private $instance;

    private function __construct(DeleteFolder $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new delete folder Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new DeleteFolder($status, $message));
    }

    /**
     * Initializes a new delete folder object.
     */
    public function build(): DeleteFolder
    {
        return CoreHelper::clone($this->instance);
    }
}
