<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\DeletePrmoptTemplate;

/**
 * Builder for model DeletePrmoptTemplate
 *
 * @see DeletePrmoptTemplate
 */
class DeletePrmoptTemplateBuilder
{
    /**
     * @var DeletePrmoptTemplate
     */
    private $instance;

    private function __construct(DeletePrmoptTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new delete prmopt template Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new DeletePrmoptTemplate($status, $message));
    }

    /**
     * Initializes a new delete prmopt template object.
     */
    public function build(): DeletePrmoptTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
