<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\DeleteCustomTemplate;

/**
 * Builder for model DeleteCustomTemplate
 *
 * @see DeleteCustomTemplate
 */
class DeleteCustomTemplateBuilder
{
    /**
     * @var DeleteCustomTemplate
     */
    private $instance;

    private function __construct(DeleteCustomTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new delete custom template Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new DeleteCustomTemplate($status, $message));
    }

    /**
     * Initializes a new delete custom template object.
     */
    public function build(): DeleteCustomTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
