<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\DeleteWorkspaceLive;

/**
 * Builder for model DeleteWorkspaceLive
 *
 * @see DeleteWorkspaceLive
 */
class DeleteWorkspaceLiveBuilder
{
    /**
     * @var DeleteWorkspaceLive
     */
    private $instance;

    private function __construct(DeleteWorkspaceLive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new delete workspace live Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new DeleteWorkspaceLive($status, $message));
    }

    /**
     * Initializes a new delete workspace live object.
     */
    public function build(): DeleteWorkspaceLive
    {
        return CoreHelper::clone($this->instance);
    }
}
