<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\ExampleWithDefaultPlanSubdomainAndSubsctpion;
use TaamAiUserLib\Models\User2;

/**
 * Builder for model ExampleWithDefaultPlanSubdomainAndSubsctpion
 *
 * @see ExampleWithDefaultPlanSubdomainAndSubsctpion
 */
class ExampleWithDefaultPlanSubdomainAndSubsctpionBuilder
{
    /**
     * @var ExampleWithDefaultPlanSubdomainAndSubsctpion
     */
    private $instance;

    private function __construct(ExampleWithDefaultPlanSubdomainAndSubsctpion $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new example with default plan subdomain and subsctpion Builder object.
     */
    public static function init(bool $result, string $message, string $accessToken, User2 $user): self
    {
        return new self(new ExampleWithDefaultPlanSubdomainAndSubsctpion($result, $message, $accessToken, $user));
    }

    /**
     * Initializes a new example with default plan subdomain and subsctpion object.
     */
    public function build(): ExampleWithDefaultPlanSubdomainAndSubsctpion
    {
        return CoreHelper::clone($this->instance);
    }
}
