<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Field;

/**
 * Builder for model Field
 *
 * @see Field
 */
class FieldBuilder
{
    /**
     * @var Field
     */
    private $instance;

    private function __construct(Field $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new field Builder object.
     */
    public static function init(string $name, string $placeholder, string $input, string $code): self
    {
        return new self(new Field($name, $placeholder, $input, $code));
    }

    /**
     * Initializes a new field object.
     */
    public function build(): Field
    {
        return CoreHelper::clone($this->instance);
    }
}
