<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\GenerateTemplateLive;

/**
 * Builder for model GenerateTemplateLive
 *
 * @see GenerateTemplateLive
 */
class GenerateTemplateLiveBuilder
{
    /**
     * @var GenerateTemplateLive
     */
    private $instance;

    private function __construct(GenerateTemplateLive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new generate template live Builder object.
     */
    public static function init(string $status, string $maxResults, string $temperature, int $maxWords, int $id): self
    {
        return new self(new GenerateTemplateLive($status, $maxResults, $temperature, $maxWords, $id));
    }

    /**
     * Initializes a new generate template live object.
     */
    public function build(): GenerateTemplateLive
    {
        return CoreHelper::clone($this->instance);
    }
}
