<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\GeneratePromptTemplate;

/**
 * Builder for model GeneratePromptTemplate
 *
 * @see GeneratePromptTemplate
 */
class GeneratePromptTemplateBuilder
{
    /**
     * @var GeneratePromptTemplate
     */
    private $instance;

    private function __construct(GeneratePromptTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new generate prompt template Builder object.
     */
    public static function init(
        string $status,
        string $maxResults,
        string $temperature,
        string $maxWords,
        int $id
    ): self {
        return new self(new GeneratePromptTemplate($status, $maxResults, $temperature, $maxWords, $id));
    }

    /**
     * Initializes a new generate prompt template object.
     */
    public function build(): GeneratePromptTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
