<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\GenerateCode;

/**
 * Builder for model GenerateCode
 *
 * @see GenerateCode
 */
class GenerateCodeBuilder
{
    /**
     * @var GenerateCode
     */
    private $instance;

    private function __construct(GenerateCode $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new generate code Builder object.
     */
    public static function init(string $text, string $status, int $id, string $old, int $current): self
    {
        return new self(new GenerateCode($text, $status, $id, $old, $current));
    }

    /**
     * Initializes a new generate code object.
     */
    public function build(): GenerateCode
    {
        return CoreHelper::clone($this->instance);
    }
}
