<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\GenerateSpeechToText;

/**
 * Builder for model GenerateSpeechToText
 *
 * @see GenerateSpeechToText
 */
class GenerateSpeechToTextBuilder
{
    /**
     * @var GenerateSpeechToText
     */
    private $instance;

    private function __construct(GenerateSpeechToText $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new generate speech to text Builder object.
     */
    public static function init(string $text, string $status, string $url, int $id, string $old, int $current): self
    {
        return new self(new GenerateSpeechToText($text, $status, $url, $id, $old, $current));
    }

    /**
     * Initializes a new generate speech to text object.
     */
    public function build(): GenerateSpeechToText
    {
        return CoreHelper::clone($this->instance);
    }
}
