<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data17;
use TaamAiUserLib\Models\GenerateImageFromAI;

/**
 * Builder for model GenerateImageFromAI
 *
 * @see GenerateImageFromAI
 */
class GenerateImageFromAIBuilder
{
    /**
     * @var GenerateImageFromAI
     */
    private $instance;

    private function __construct(GenerateImageFromAI $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new generate image from ai Builder object.
     */
    public static function init(string $status, string $old, int $current, Data17 $data): self
    {
        return new self(new GenerateImageFromAI($status, $old, $current, $data));
    }

    /**
     * Initializes a new generate image from ai object.
     */
    public function build(): GenerateImageFromAI
    {
        return CoreHelper::clone($this->instance);
    }
}
