<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\JoinWorkbookRequestr;

/**
 * Builder for model JoinWorkbookRequestr
 *
 * @see JoinWorkbookRequestr
 */
class JoinWorkbookRequestrBuilder
{
    /**
     * @var JoinWorkbookRequestr
     */
    private $instance;

    private function __construct(JoinWorkbookRequestr $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new join workbook requestr Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new JoinWorkbookRequestr($status, $message));
    }

    /**
     * Initializes a new join workbook requestr object.
     */
    public function build(): JoinWorkbookRequestr
    {
        return CoreHelper::clone($this->instance);
    }
}
