<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\JoinWorkbook;

/**
 * Builder for model JoinWorkbook
 *
 * @see JoinWorkbook
 */
class JoinWorkbookBuilder
{
    /**
     * @var JoinWorkbook
     */
    private $instance;

    private function __construct(JoinWorkbook $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new join workbook Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new JoinWorkbook($status, $message));
    }

    /**
     * Initializes a new join workbook object.
     */
    public function build(): JoinWorkbook
    {
        return CoreHelper::clone($this->instance);
    }
}
