<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\LoginLive;
use TaamAiUserLib\Models\User;

/**
 * Builder for model LoginLive
 *
 * @see LoginLive
 */
class LoginLiveBuilder
{
    /**
     * @var LoginLive
     */
    private $instance;

    private function __construct(LoginLive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new login live Builder object.
     */
    public static function init(
        bool $status,
        string $message,
        string $accessToken,
        string $tokenType,
        User $user
    ): self {
        return new self(new LoginLive($status, $message, $accessToken, $tokenType, $user));
    }

    /**
     * Sets expires at field.
     */
    public function expiresAt(?string $value): self
    {
        $this->instance->setExpiresAt($value);
        return $this;
    }

    /**
     * Initializes a new login live object.
     */
    public function build(): LoginLive
    {
        return CoreHelper::clone($this->instance);
    }
}
