<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\NewRequest1;

/**
 * Builder for model NewRequest1
 *
 * @see NewRequest1
 */
class NewRequest1Builder
{
    /**
     * @var NewRequest1
     */
    private $instance;

    private function __construct(NewRequest1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new new request 1 Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new NewRequest1($status, $message));
    }

    /**
     * Initializes a new new request 1 object.
     */
    public function build(): NewRequest1
    {
        return CoreHelper::clone($this->instance);
    }
}
