<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\ParmanentDeletePromptTemplate;

/**
 * Builder for model ParmanentDeletePromptTemplate
 *
 * @see ParmanentDeletePromptTemplate
 */
class ParmanentDeletePromptTemplateBuilder
{
    /**
     * @var ParmanentDeletePromptTemplate
     */
    private $instance;

    private function __construct(ParmanentDeletePromptTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new parmanent delete prompt template Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new ParmanentDeletePromptTemplate($status, $message));
    }

    /**
     * Initializes a new parmanent delete prompt template object.
     */
    public function build(): ParmanentDeletePromptTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
