<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\PermanentDeleteCustomTemplate;

/**
 * Builder for model PermanentDeleteCustomTemplate
 *
 * @see PermanentDeleteCustomTemplate
 */
class PermanentDeleteCustomTemplateBuilder
{
    /**
     * @var PermanentDeleteCustomTemplate
     */
    private $instance;

    private function __construct(PermanentDeleteCustomTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new permanent delete custom template Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new PermanentDeleteCustomTemplate($status, $message));
    }

    /**
     * Initializes a new permanent delete custom template object.
     */
    public function build(): PermanentDeleteCustomTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
