<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\PermanentDeleteDocument;

/**
 * Builder for model PermanentDeleteDocument
 *
 * @see PermanentDeleteDocument
 */
class PermanentDeleteDocumentBuilder
{
    /**
     * @var PermanentDeleteDocument
     */
    private $instance;

    private function __construct(PermanentDeleteDocument $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new permanent delete document Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new PermanentDeleteDocument($status, $message));
    }

    /**
     * Initializes a new permanent delete document object.
     */
    public function build(): PermanentDeleteDocument
    {
        return CoreHelper::clone($this->instance);
    }
}
