<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\ProcessTemplate;

/**
 * Builder for model ProcessTemplate
 *
 * @see ProcessTemplate
 */
class ProcessTemplateBuilder
{
    /**
     * @var ProcessTemplate
     */
    private $instance;

    private function __construct(ProcessTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new process template Builder object.
     */
    public static function init(string $status, string $data): self
    {
        return new self(new ProcessTemplate($status, $data));
    }

    /**
     * Initializes a new process template object.
     */
    public function build(): ProcessTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
