<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\PromptTemplateLikeOrRemoveFromLike;

/**
 * Builder for model PromptTemplateLikeOrRemoveFromLike
 *
 * @see PromptTemplateLikeOrRemoveFromLike
 */
class PromptTemplateLikeOrRemoveFromLikeBuilder
{
    /**
     * @var PromptTemplateLikeOrRemoveFromLike
     */
    private $instance;

    private function __construct(PromptTemplateLikeOrRemoveFromLike $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new prompt template like or remove from like Builder object.
     */
    public static function init(string $status, string $message, int $count): self
    {
        return new self(new PromptTemplateLikeOrRemoveFromLike($status, $message, $count));
    }

    /**
     * Initializes a new prompt template like or remove from like object.
     */
    public function build(): PromptTemplateLikeOrRemoveFromLike
    {
        return CoreHelper::clone($this->instance);
    }
}
