<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\PromptTemplates;

/**
 * Builder for model PromptTemplates
 *
 * @see PromptTemplates
 */
class PromptTemplatesBuilder
{
    /**
     * @var PromptTemplates
     */
    private $instance;

    private function __construct(PromptTemplates $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new prompt templates Builder object.
     */
    public static function init(string $status, string $message, array $data): self
    {
        return new self(new PromptTemplates($status, $message, $data));
    }

    /**
     * Initializes a new prompt templates object.
     */
    public function build(): PromptTemplates
    {
        return CoreHelper::clone($this->instance);
    }
}
