<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\RejectWorkbook;

/**
 * Builder for model RejectWorkbook
 *
 * @see RejectWorkbook
 */
class RejectWorkbookBuilder
{
    /**
     * @var RejectWorkbook
     */
    private $instance;

    private function __construct(RejectWorkbook $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new reject workbook Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new RejectWorkbook($status, $message));
    }

    /**
     * Initializes a new reject workbook object.
     */
    public function build(): RejectWorkbook
    {
        return CoreHelper::clone($this->instance);
    }
}
