<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\RestorePromptTemplate;

/**
 * Builder for model RestorePromptTemplate
 *
 * @see RestorePromptTemplate
 */
class RestorePromptTemplateBuilder
{
    /**
     * @var RestorePromptTemplate
     */
    private $instance;

    private function __construct(RestorePromptTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new restore prompt template Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new RestorePromptTemplate($status, $message));
    }

    /**
     * Initializes a new restore prompt template object.
     */
    public function build(): RestorePromptTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
