<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\RestoreProduct;

/**
 * Builder for model RestoreProduct
 *
 * @see RestoreProduct
 */
class RestoreProductBuilder
{
    /**
     * @var RestoreProduct
     */
    private $instance;

    private function __construct(RestoreProduct $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new restore product Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new RestoreProduct($status, $message));
    }

    /**
     * Initializes a new restore product object.
     */
    public function build(): RestoreProduct
    {
        return CoreHelper::clone($this->instance);
    }
}
