<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\RestoreWorkspaceLive;

/**
 * Builder for model RestoreWorkspaceLive
 *
 * @see RestoreWorkspaceLive
 */
class RestoreWorkspaceLiveBuilder
{
    /**
     * @var RestoreWorkspaceLive
     */
    private $instance;

    private function __construct(RestoreWorkspaceLive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new restore workspace live Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new RestoreWorkspaceLive($status, $message));
    }

    /**
     * Initializes a new restore workspace live object.
     */
    public function build(): RestoreWorkspaceLive
    {
        return CoreHelper::clone($this->instance);
    }
}
