<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\RestoreCustomTemplate;

/**
 * Builder for model RestoreCustomTemplate
 *
 * @see RestoreCustomTemplate
 */
class RestoreCustomTemplateBuilder
{
    /**
     * @var RestoreCustomTemplate
     */
    private $instance;

    private function __construct(RestoreCustomTemplate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new restore custom template Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new RestoreCustomTemplate($status, $message));
    }

    /**
     * Initializes a new restore custom template object.
     */
    public function build(): RestoreCustomTemplate
    {
        return CoreHelper::clone($this->instance);
    }
}
