<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\RestoreDocuemntOfAllTypeContentVoiceoverImagesTranscriptCode;

/**
 * Builder for model RestoreDocuemntOfAllTypeContentVoiceoverImagesTranscriptCode
 *
 * @see RestoreDocuemntOfAllTypeContentVoiceoverImagesTranscriptCode
 */
class RestoreDocuemntOfAllTypeContentVoiceoverImagesTranscriptCodeBuilder
{
    /**
     * @var RestoreDocuemntOfAllTypeContentVoiceoverImagesTranscriptCode
     */
    private $instance;

    private function __construct(RestoreDocuemntOfAllTypeContentVoiceoverImagesTranscriptCode $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new restore docuemnt of all type content voiceover images transcript code Builder
     * object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new RestoreDocuemntOfAllTypeContentVoiceoverImagesTranscriptCode($status, $message));
    }

    /**
     * Initializes a new restore docuemnt of all type content voiceover images transcript code object.
     */
    public function build(): RestoreDocuemntOfAllTypeContentVoiceoverImagesTranscriptCode
    {
        return CoreHelper::clone($this->instance);
    }
}
