<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Pivot;
use TaamAiUserLib\Models\Role;

/**
 * Builder for model Role
 *
 * @see Role
 */
class RoleBuilder
{
    /**
     * @var Role
     */
    private $instance;

    private function __construct(Role $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new role Builder object.
     */
    public static function init(
        int $id,
        string $name,
        string $guardName,
        string $createdAt,
        string $updatedAt,
        Pivot $pivot
    ): self {
        return new self(new Role($id, $name, $guardName, $createdAt, $updatedAt, $pivot));
    }

    /**
     * Initializes a new role object.
     */
    public function build(): Role
    {
        return CoreHelper::clone($this->instance);
    }
}
