<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\SaveCodeInWorkspace;

/**
 * Builder for model SaveCodeInWorkspace
 *
 * @see SaveCodeInWorkspace
 */
class SaveCodeInWorkspaceBuilder
{
    /**
     * @var SaveCodeInWorkspace
     */
    private $instance;

    private function __construct(SaveCodeInWorkspace $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new save code in workspace Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new SaveCodeInWorkspace($status, $message));
    }

    /**
     * Initializes a new save code in workspace object.
     */
    public function build(): SaveCodeInWorkspace
    {
        return CoreHelper::clone($this->instance);
    }
}
