<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\TrashedPromptTemplates;

/**
 * Builder for model TrashedPromptTemplates
 *
 * @see TrashedPromptTemplates
 */
class TrashedPromptTemplatesBuilder
{
    /**
     * @var TrashedPromptTemplates
     */
    private $instance;

    private function __construct(TrashedPromptTemplates $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new trashed prompt templates Builder object.
     */
    public static function init(string $status, string $message, array $data): self
    {
        return new self(new TrashedPromptTemplates($status, $message, $data));
    }

    /**
     * Initializes a new trashed prompt templates object.
     */
    public function build(): TrashedPromptTemplates
    {
        return CoreHelper::clone($this->instance);
    }
}
