<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\TrashedWorkspacesLive;

/**
 * Builder for model TrashedWorkspacesLive
 *
 * @see TrashedWorkspacesLive
 */
class TrashedWorkspacesLiveBuilder
{
    /**
     * @var TrashedWorkspacesLive
     */
    private $instance;

    private function __construct(TrashedWorkspacesLive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new trashed workspaces live Builder object.
     */
    public static function init(string $status, string $message, array $data): self
    {
        return new self(new TrashedWorkspacesLive($status, $message, $data));
    }

    /**
     * Initializes a new trashed workspaces live object.
     */
    public function build(): TrashedWorkspacesLive
    {
        return CoreHelper::clone($this->instance);
    }
}
