<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\TrashedCustomTemplates;

/**
 * Builder for model TrashedCustomTemplates
 *
 * @see TrashedCustomTemplates
 */
class TrashedCustomTemplatesBuilder
{
    /**
     * @var TrashedCustomTemplates
     */
    private $instance;

    private function __construct(TrashedCustomTemplates $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new trashed custom templates Builder object.
     */
    public static function init(string $status, string $message, array $data): self
    {
        return new self(new TrashedCustomTemplates($status, $message, $data));
    }

    /**
     * Initializes a new trashed custom templates object.
     */
    public function build(): TrashedCustomTemplates
    {
        return CoreHelper::clone($this->instance);
    }
}
