<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\UpdateProduct;

/**
 * Builder for model UpdateProduct
 *
 * @see UpdateProduct
 */
class UpdateProductBuilder
{
    /**
     * @var UpdateProduct
     */
    private $instance;

    private function __construct(UpdateProduct $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new update product Builder object.
     */
    public static function init(string $status, string $message): self
    {
        return new self(new UpdateProduct($status, $message));
    }

    /**
     * Initializes a new update product object.
     */
    public function build(): UpdateProduct
    {
        return CoreHelper::clone($this->instance);
    }
}
