<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\UserChats;

/**
 * Builder for model UserChats
 *
 * @see UserChats
 */
class UserChatsBuilder
{
    /**
     * @var UserChats
     */
    private $instance;

    private function __construct(UserChats $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new user chats Builder object.
     */
    public static function init(string $status, string $message, int $count, array $data): self
    {
        return new self(new UserChats($status, $message, $count, $data));
    }

    /**
     * Initializes a new user chats object.
     */
    public function build(): UserChats
    {
        return CoreHelper::clone($this->instance);
    }
}
