<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\User2;

/**
 * Builder for model User2
 *
 * @see User2
 */
class User2Builder
{
    /**
     * @var User2
     */
    private $instance;

    private function __construct(User2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new user 2 Builder object.
     */
    public static function init(
        string $name,
        string $email,
        string $country,
        string $updatedAt,
        string $createdAt,
        int $id,
        string $emailVerifiedAt,
        string $status,
        string $group,
        string $availableWordsPrepaid,
        string $availableImagesPrepaid,
        string $availableCharsPrepaid,
        string $availableMinutesPrepaid,
        string $defaultVoiceoverLanguage,
        string $defaultVoiceoverVoice,
        string $jobRole,
        string $referralId,
        string $referredBy,
        string $workbook,
        int $workbookId,
        int $workbookFolderId,
        int $planId,
        int $totalWords,
        int $totalImages,
        int $totalChars,
        int $totalMinutes,
        int $availableWords,
        int $availableImages,
        int $availableChars,
        int $availableMinutes,
        array $roles
    ): self {
        return new self(new User2(
            $name,
            $email,
            $country,
            $updatedAt,
            $createdAt,
            $id,
            $emailVerifiedAt,
            $status,
            $group,
            $availableWordsPrepaid,
            $availableImagesPrepaid,
            $availableCharsPrepaid,
            $availableMinutesPrepaid,
            $defaultVoiceoverLanguage,
            $defaultVoiceoverVoice,
            $jobRole,
            $referralId,
            $referredBy,
            $workbook,
            $workbookId,
            $workbookFolderId,
            $planId,
            $totalWords,
            $totalImages,
            $totalChars,
            $totalMinutes,
            $availableWords,
            $availableImages,
            $availableChars,
            $availableMinutes,
            $roles
        ));
    }

    /**
     * Initializes a new user 2 object.
     */
    public function build(): User2
    {
        return CoreHelper::clone($this->instance);
    }
}
