<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\WorkbookVoiceovers;

/**
 * Builder for model WorkbookVoiceovers
 *
 * @see WorkbookVoiceovers
 */
class WorkbookVoiceoversBuilder
{
    /**
     * @var WorkbookVoiceovers
     */
    private $instance;

    private function __construct(WorkbookVoiceovers $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new workbook voiceovers Builder object.
     */
    public static function init(string $status, string $message, int $count, array $data): self
    {
        return new self(new WorkbookVoiceovers($status, $message, $count, $data));
    }

    /**
     * Initializes a new workbook voiceovers object.
     */
    public function build(): WorkbookVoiceovers
    {
        return CoreHelper::clone($this->instance);
    }
}
