<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\WorkbookImages;

/**
 * Builder for model WorkbookImages
 *
 * @see WorkbookImages
 */
class WorkbookImagesBuilder
{
    /**
     * @var WorkbookImages
     */
    private $instance;

    private function __construct(WorkbookImages $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new workbook images Builder object.
     */
    public static function init(string $status, string $message, int $count, array $data): self
    {
        return new self(new WorkbookImages($status, $message, $count, $data));
    }

    /**
     * Initializes a new workbook images object.
     */
    public function build(): WorkbookImages
    {
        return CoreHelper::clone($this->instance);
    }
}
