<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\WorkbookTranscripts;

/**
 * Builder for model WorkbookTranscripts
 *
 * @see WorkbookTranscripts
 */
class WorkbookTranscriptsBuilder
{
    /**
     * @var WorkbookTranscripts
     */
    private $instance;

    private function __construct(WorkbookTranscripts $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new workbook transcripts Builder object.
     */
    public static function init(string $status, string $message, int $count, array $data): self
    {
        return new self(new WorkbookTranscripts($status, $message, $count, $data));
    }

    /**
     * Initializes a new workbook transcripts object.
     */
    public function build(): WorkbookTranscripts
    {
        return CoreHelper::clone($this->instance);
    }
}
