<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\WorkbookPolicies;

/**
 * Builder for model WorkbookPolicies
 *
 * @see WorkbookPolicies
 */
class WorkbookPoliciesBuilder
{
    /**
     * @var WorkbookPolicies
     */
    private $instance;

    private function __construct(WorkbookPolicies $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new workbook policies Builder object.
     */
    public static function init(string $status, string $message, int $count, array $data): self
    {
        return new self(new WorkbookPolicies($status, $message, $count, $data));
    }

    /**
     * Initializes a new workbook policies object.
     */
    public function build(): WorkbookPolicies
    {
        return CoreHelper::clone($this->instance);
    }
}
