<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models\Builders;

use Core\Utils\CoreHelper;
use TaamAiUserLib\Models\Data1;
use TaamAiUserLib\Models\WorkbookDetailLive;

/**
 * Builder for model WorkbookDetailLive
 *
 * @see WorkbookDetailLive
 */
class WorkbookDetailLiveBuilder
{
    /**
     * @var WorkbookDetailLive
     */
    private $instance;

    private function __construct(WorkbookDetailLive $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new workbook detail live Builder object.
     */
    public static function init(string $status, string $message, Data1 $data): self
    {
        return new self(new WorkbookDetailLive($status, $message, $data));
    }

    /**
     * Initializes a new workbook detail live object.
     */
    public function build(): WorkbookDetailLive
    {
        return CoreHelper::clone($this->instance);
    }
}
