<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Http;

use Core\Types\Sdk\CoreCallback;

/**
 * HttpCallBack allows defining callables for pre and post API calls.
 */
class HttpCallBack extends CoreCallback
{
}
