<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Controllers;

use Core\Request\Parameters\FormParam;
use Core\Request\Parameters\QueryParam;
use CoreInterfaces\Core\Request\RequestMethod;
use TaamAiUserLib\Exceptions\ApiException;
use TaamAiUserLib\Models\ExampleWithDefaultPlanSubdomainAndSubsctpion;
use TaamAiUserLib\Models\Login;

class AuthController extends BaseController
{
    /**
     * @param string $email
     * @param string $password
     *
     * @return Login Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function login(string $email, string $password): Login
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/login')
            ->auth('global')
            ->parameters(FormParam::init('email', $email), FormParam::init('password', $password));

        $_resHandler = $this->responseHandler()->type(Login::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }

    /**
     * @param string $name
     * @param string $email
     * @param string $password
     * @param string $country
     * @param string $subdomain
     *
     * @return ExampleWithDefaultPlanSubdomainAndSubsctpion Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function register(
        string $name,
        string $email,
        string $password,
        string $country,
        string $subdomain
    ): ExampleWithDefaultPlanSubdomainAndSubsctpion {
        $_reqBuilder = $this->requestBuilder(RequestMethod::POST, '/register')
            ->auth('global')
            ->parameters(
                QueryParam::init('name', $name),
                QueryParam::init('email', $email),
                QueryParam::init('password', $password),
                QueryParam::init('country', $country),
                QueryParam::init('subdomain', $subdomain)
            );

        $_resHandler = $this->responseHandler()->type(ExampleWithDefaultPlanSubdomainAndSubsctpion::class);

        return $this->execute($_reqBuilder, $_resHandler);
    }
}
