<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models;

use stdClass;

class Data15 implements \JsonSerializable
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var int
     */
    private $userId;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $icon;

    /**
     * @var string|null
     */
    private $image;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $templateCode;

    /**
     * @var string
     */
    private $lang;

    /**
     * @var int
     */
    private $status;

    /**
     * @var int
     */
    private $professional;

    /**
     * @var int
     */
    private $new;

    /**
     * @var int
     */
    private $public;

    /**
     * @var int
     */
    private $edit;

    /**
     * @var string
     */
    private $group;

    /**
     * @var string
     */
    private $slug;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string|null
     */
    private $prompt;

    /**
     * @var int
     */
    private $tone;

    /**
     * @var string[]
     */
    private $fields;

    /**
     * @var string
     */
    private $package;

    /**
     * @var string
     */
    private $createdAt;

    /**
     * @var string
     */
    private $updatedAt;

    /**
     * @var string|null
     */
    private $deletedAt;

    /**
     * @param int $id
     * @param int $userId
     * @param string $name
     * @param string $icon
     * @param string $description
     * @param string $templateCode
     * @param string $lang
     * @param int $status
     * @param int $professional
     * @param int $new
     * @param int $public
     * @param int $edit
     * @param string $group
     * @param string $slug
     * @param string $type
     * @param int $tone
     * @param string[] $fields
     * @param string $package
     * @param string $createdAt
     * @param string $updatedAt
     */
    public function __construct(
        int $id,
        int $userId,
        string $name,
        string $icon,
        string $description,
        string $templateCode,
        string $lang,
        int $status,
        int $professional,
        int $new,
        int $public,
        int $edit,
        string $group,
        string $slug,
        string $type,
        int $tone,
        array $fields,
        string $package,
        string $createdAt,
        string $updatedAt
    ) {
        $this->id = $id;
        $this->userId = $userId;
        $this->name = $name;
        $this->icon = $icon;
        $this->description = $description;
        $this->templateCode = $templateCode;
        $this->lang = $lang;
        $this->status = $status;
        $this->professional = $professional;
        $this->new = $new;
        $this->public = $public;
        $this->edit = $edit;
        $this->group = $group;
        $this->slug = $slug;
        $this->type = $type;
        $this->tone = $tone;
        $this->fields = $fields;
        $this->package = $package;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns User Id.
     */
    public function getUserId(): int
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     *
     * @required
     * @maps user_id
     */
    public function setUserId(int $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Icon.
     */
    public function getIcon(): string
    {
        return $this->icon;
    }

    /**
     * Sets Icon.
     *
     * @required
     * @maps icon
     */
    public function setIcon(string $icon): void
    {
        $this->icon = $icon;
    }

    /**
     * Returns Image.
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * Sets Image.
     *
     * @maps image
     */
    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Template Code.
     */
    public function getTemplateCode(): string
    {
        return $this->templateCode;
    }

    /**
     * Sets Template Code.
     *
     * @required
     * @maps template_code
     */
    public function setTemplateCode(string $templateCode): void
    {
        $this->templateCode = $templateCode;
    }

    /**
     * Returns Lang.
     */
    public function getLang(): string
    {
        return $this->lang;
    }

    /**
     * Sets Lang.
     *
     * @required
     * @maps lang
     */
    public function setLang(string $lang): void
    {
        $this->lang = $lang;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): int
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(int $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Professional.
     */
    public function getProfessional(): int
    {
        return $this->professional;
    }

    /**
     * Sets Professional.
     *
     * @required
     * @maps professional
     */
    public function setProfessional(int $professional): void
    {
        $this->professional = $professional;
    }

    /**
     * Returns New.
     */
    public function getNew(): int
    {
        return $this->new;
    }

    /**
     * Sets New.
     *
     * @required
     * @maps new
     */
    public function setNew(int $new): void
    {
        $this->new = $new;
    }

    /**
     * Returns Public.
     */
    public function getPublic(): int
    {
        return $this->public;
    }

    /**
     * Sets Public.
     *
     * @required
     * @maps public
     */
    public function setPublic(int $public): void
    {
        $this->public = $public;
    }

    /**
     * Returns Edit.
     */
    public function getEdit(): int
    {
        return $this->edit;
    }

    /**
     * Sets Edit.
     *
     * @required
     * @maps edit
     */
    public function setEdit(int $edit): void
    {
        $this->edit = $edit;
    }

    /**
     * Returns Group.
     */
    public function getGroup(): string
    {
        return $this->group;
    }

    /**
     * Sets Group.
     *
     * @required
     * @maps group
     */
    public function setGroup(string $group): void
    {
        $this->group = $group;
    }

    /**
     * Returns Slug.
     */
    public function getSlug(): string
    {
        return $this->slug;
    }

    /**
     * Sets Slug.
     *
     * @required
     * @maps slug
     */
    public function setSlug(string $slug): void
    {
        $this->slug = $slug;
    }

    /**
     * Returns Type.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @required
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Prompt.
     */
    public function getPrompt(): ?string
    {
        return $this->prompt;
    }

    /**
     * Sets Prompt.
     *
     * @maps prompt
     */
    public function setPrompt(?string $prompt): void
    {
        $this->prompt = $prompt;
    }

    /**
     * Returns Tone.
     */
    public function getTone(): int
    {
        return $this->tone;
    }

    /**
     * Sets Tone.
     *
     * @required
     * @maps tone
     */
    public function setTone(int $tone): void
    {
        $this->tone = $tone;
    }

    /**
     * Returns Fields.
     *
     * @return string[]
     */
    public function getFields(): array
    {
        return $this->fields;
    }

    /**
     * Sets Fields.
     *
     * @required
     * @maps fields
     *
     * @param string[] $fields
     */
    public function setFields(array $fields): void
    {
        $this->fields = $fields;
    }

    /**
     * Returns Package.
     */
    public function getPackage(): string
    {
        return $this->package;
    }

    /**
     * Sets Package.
     *
     * @required
     * @maps package
     */
    public function setPackage(string $package): void
    {
        $this->package = $package;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): string
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     */
    public function setCreatedAt(string $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): string
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @required
     * @maps updated_at
     */
    public function setUpdatedAt(string $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Deleted At.
     */
    public function getDeletedAt(): ?string
    {
        return $this->deletedAt;
    }

    /**
     * Sets Deleted At.
     *
     * @maps deleted_at
     */
    public function setDeletedAt(?string $deletedAt): void
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']            = $this->id;
        $json['user_id']       = $this->userId;
        $json['name']          = $this->name;
        $json['icon']          = $this->icon;
        $json['image']         = $this->image;
        $json['description']   = $this->description;
        $json['template_code'] = $this->templateCode;
        $json['lang']          = $this->lang;
        $json['status']        = $this->status;
        $json['professional']  = $this->professional;
        $json['new']           = $this->new;
        $json['public']        = $this->public;
        $json['edit']          = $this->edit;
        $json['group']         = $this->group;
        $json['slug']          = $this->slug;
        $json['type']          = $this->type;
        $json['prompt']        = $this->prompt;
        $json['tone']          = $this->tone;
        $json['fields']        = $this->fields;
        $json['package']       = $this->package;
        $json['created_at']    = $this->createdAt;
        $json['updated_at']    = $this->updatedAt;
        $json['deleted_at']    = $this->deletedAt;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
