<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models;

use stdClass;

class Data1 implements \JsonSerializable
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var int
     */
    private $userId;

    /**
     * @var string
     */
    private $name;

    /**
     * @var int
     */
    private $default;

    /**
     * @var string
     */
    private $createdAt;

    /**
     * @var string
     */
    private $updatedAt;

    /**
     * @var string|null
     */
    private $deletedAt;

    /**
     * @var Folder2[]
     */
    private $folders;

    /**
     * @param int $id
     * @param int $userId
     * @param string $name
     * @param int $default
     * @param string $createdAt
     * @param string $updatedAt
     * @param Folder2[] $folders
     */
    public function __construct(
        int $id,
        int $userId,
        string $name,
        int $default,
        string $createdAt,
        string $updatedAt,
        array $folders
    ) {
        $this->id = $id;
        $this->userId = $userId;
        $this->name = $name;
        $this->default = $default;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->folders = $folders;
    }

    /**
     * Returns Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns User Id.
     */
    public function getUserId(): int
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     *
     * @required
     * @maps user_id
     */
    public function setUserId(int $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Default.
     */
    public function getDefault(): int
    {
        return $this->default;
    }

    /**
     * Sets Default.
     *
     * @required
     * @maps default
     */
    public function setDefault(int $default): void
    {
        $this->default = $default;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): string
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     */
    public function setCreatedAt(string $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): string
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @required
     * @maps updated_at
     */
    public function setUpdatedAt(string $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Deleted At.
     */
    public function getDeletedAt(): ?string
    {
        return $this->deletedAt;
    }

    /**
     * Sets Deleted At.
     *
     * @maps deleted_at
     */
    public function setDeletedAt(?string $deletedAt): void
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * Returns Folders.
     *
     * @return Folder2[]
     */
    public function getFolders(): array
    {
        return $this->folders;
    }

    /**
     * Sets Folders.
     *
     * @required
     * @maps folders
     *
     * @param Folder2[] $folders
     */
    public function setFolders(array $folders): void
    {
        $this->folders = $folders;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']         = $this->id;
        $json['user_id']    = $this->userId;
        $json['name']       = $this->name;
        $json['default']    = $this->default;
        $json['created_at'] = $this->createdAt;
        $json['updated_at'] = $this->updatedAt;
        $json['deleted_at'] = $this->deletedAt;
        $json['folders']    = $this->folders;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
