<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models;

use stdClass;

class Data8 implements \JsonSerializable
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var int
     */
    private $userId;

    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $description;

    /**
     * @var string
     */
    private $image;

    /**
     * @var int
     */
    private $workbookId;

    /**
     * @var int
     */
    private $workbookFolderId;

    /**
     * @var string
     */
    private $storage;

    /**
     * @var string
     */
    private $imageName;

    /**
     * @var string
     */
    private $resolution;

    /**
     * @var string
     */
    private $planType;

    /**
     * @var string
     */
    private $expiresAt;

    /**
     * @var string
     */
    private $createdAt;

    /**
     * @var string
     */
    private $updatedAt;

    /**
     * @var string|null
     */
    private $deletedAt;

    /**
     * @param int $id
     * @param int $userId
     * @param string $name
     * @param string $description
     * @param string $image
     * @param int $workbookId
     * @param int $workbookFolderId
     * @param string $storage
     * @param string $imageName
     * @param string $resolution
     * @param string $planType
     * @param string $expiresAt
     * @param string $createdAt
     * @param string $updatedAt
     */
    public function __construct(
        int $id,
        int $userId,
        string $name,
        string $description,
        string $image,
        int $workbookId,
        int $workbookFolderId,
        string $storage,
        string $imageName,
        string $resolution,
        string $planType,
        string $expiresAt,
        string $createdAt,
        string $updatedAt
    ) {
        $this->id = $id;
        $this->userId = $userId;
        $this->name = $name;
        $this->description = $description;
        $this->image = $image;
        $this->workbookId = $workbookId;
        $this->workbookFolderId = $workbookFolderId;
        $this->storage = $storage;
        $this->imageName = $imageName;
        $this->resolution = $resolution;
        $this->planType = $planType;
        $this->expiresAt = $expiresAt;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns User Id.
     */
    public function getUserId(): int
    {
        return $this->userId;
    }

    /**
     * Sets User Id.
     *
     * @required
     * @maps user_id
     */
    public function setUserId(int $userId): void
    {
        $this->userId = $userId;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @required
     * @maps description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Image.
     */
    public function getImage(): string
    {
        return $this->image;
    }

    /**
     * Sets Image.
     *
     * @required
     * @maps image
     */
    public function setImage(string $image): void
    {
        $this->image = $image;
    }

    /**
     * Returns Workbook Id.
     */
    public function getWorkbookId(): int
    {
        return $this->workbookId;
    }

    /**
     * Sets Workbook Id.
     *
     * @required
     * @maps workbook_id
     */
    public function setWorkbookId(int $workbookId): void
    {
        $this->workbookId = $workbookId;
    }

    /**
     * Returns Workbook Folder Id.
     */
    public function getWorkbookFolderId(): int
    {
        return $this->workbookFolderId;
    }

    /**
     * Sets Workbook Folder Id.
     *
     * @required
     * @maps workbook_folder_id
     */
    public function setWorkbookFolderId(int $workbookFolderId): void
    {
        $this->workbookFolderId = $workbookFolderId;
    }

    /**
     * Returns Storage.
     */
    public function getStorage(): string
    {
        return $this->storage;
    }

    /**
     * Sets Storage.
     *
     * @required
     * @maps storage
     */
    public function setStorage(string $storage): void
    {
        $this->storage = $storage;
    }

    /**
     * Returns Image Name.
     */
    public function getImageName(): string
    {
        return $this->imageName;
    }

    /**
     * Sets Image Name.
     *
     * @required
     * @maps image_name
     */
    public function setImageName(string $imageName): void
    {
        $this->imageName = $imageName;
    }

    /**
     * Returns Resolution.
     */
    public function getResolution(): string
    {
        return $this->resolution;
    }

    /**
     * Sets Resolution.
     *
     * @required
     * @maps resolution
     */
    public function setResolution(string $resolution): void
    {
        $this->resolution = $resolution;
    }

    /**
     * Returns Plan Type.
     */
    public function getPlanType(): string
    {
        return $this->planType;
    }

    /**
     * Sets Plan Type.
     *
     * @required
     * @maps plan_type
     */
    public function setPlanType(string $planType): void
    {
        $this->planType = $planType;
    }

    /**
     * Returns Expires At.
     */
    public function getExpiresAt(): string
    {
        return $this->expiresAt;
    }

    /**
     * Sets Expires At.
     *
     * @required
     * @maps expires_at
     */
    public function setExpiresAt(string $expiresAt): void
    {
        $this->expiresAt = $expiresAt;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): string
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     */
    public function setCreatedAt(string $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): string
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @required
     * @maps updated_at
     */
    public function setUpdatedAt(string $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Deleted At.
     */
    public function getDeletedAt(): ?string
    {
        return $this->deletedAt;
    }

    /**
     * Sets Deleted At.
     *
     * @maps deleted_at
     */
    public function setDeletedAt(?string $deletedAt): void
    {
        $this->deletedAt = $deletedAt;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['id']                 = $this->id;
        $json['user_id']            = $this->userId;
        $json['name']               = $this->name;
        $json['description']        = $this->description;
        $json['image']              = $this->image;
        $json['workbook_id']        = $this->workbookId;
        $json['workbook_folder_id'] = $this->workbookFolderId;
        $json['storage']            = $this->storage;
        $json['image_name']         = $this->imageName;
        $json['resolution']         = $this->resolution;
        $json['plan_type']          = $this->planType;
        $json['expires_at']         = $this->expiresAt;
        $json['created_at']         = $this->createdAt;
        $json['updated_at']         = $this->updatedAt;
        $json['deleted_at']         = $this->deletedAt;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
