<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models;

use stdClass;

class GenerateImageFromAI implements \JsonSerializable
{
    /**
     * @var string
     */
    private $status;

    /**
     * @var string
     */
    private $old;

    /**
     * @var int
     */
    private $current;

    /**
     * @var Data17
     */
    private $data;

    /**
     * @param string $status
     * @param string $old
     * @param int $current
     * @param Data17 $data
     */
    public function __construct(string $status, string $old, int $current, Data17 $data)
    {
        $this->status = $status;
        $this->old = $old;
        $this->current = $current;
        $this->data = $data;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Old.
     */
    public function getOld(): string
    {
        return $this->old;
    }

    /**
     * Sets Old.
     *
     * @required
     * @maps old
     */
    public function setOld(string $old): void
    {
        $this->old = $old;
    }

    /**
     * Returns Current.
     */
    public function getCurrent(): int
    {
        return $this->current;
    }

    /**
     * Sets Current.
     *
     * @required
     * @maps current
     */
    public function setCurrent(int $current): void
    {
        $this->current = $current;
    }

    /**
     * Returns Data.
     */
    public function getData(): Data17
    {
        return $this->data;
    }

    /**
     * Sets Data.
     *
     * @required
     * @maps data
     */
    public function setData(Data17 $data): void
    {
        $this->data = $data;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['status']  = $this->status;
        $json['old']     = $this->old;
        $json['current'] = $this->current;
        $json['data']    = $this->data;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
