<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models;

use stdClass;

class GenerateCode implements \JsonSerializable
{
    /**
     * @var string
     */
    private $text;

    /**
     * @var string
     */
    private $status;

    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $old;

    /**
     * @var int
     */
    private $current;

    /**
     * @param string $text
     * @param string $status
     * @param int $id
     * @param string $old
     * @param int $current
     */
    public function __construct(string $text, string $status, int $id, string $old, int $current)
    {
        $this->text = $text;
        $this->status = $status;
        $this->id = $id;
        $this->old = $old;
        $this->current = $current;
    }

    /**
     * Returns Text.
     */
    public function getText(): string
    {
        return $this->text;
    }

    /**
     * Sets Text.
     *
     * @required
     * @maps text
     */
    public function setText(string $text): void
    {
        $this->text = $text;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Old.
     */
    public function getOld(): string
    {
        return $this->old;
    }

    /**
     * Sets Old.
     *
     * @required
     * @maps old
     */
    public function setOld(string $old): void
    {
        $this->old = $old;
    }

    /**
     * Returns Current.
     */
    public function getCurrent(): int
    {
        return $this->current;
    }

    /**
     * Sets Current.
     *
     * @required
     * @maps current
     */
    public function setCurrent(int $current): void
    {
        $this->current = $current;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['text']    = $this->text;
        $json['status']  = $this->status;
        $json['id']      = $this->id;
        $json['old']     = $this->old;
        $json['current'] = $this->current;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
