<?php

declare(strict_types=1);

/*
 * TaamAiUserLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace TaamAiUserLib\Models;

use stdClass;

class User2 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $name;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $country;

    /**
     * @var string
     */
    private $updatedAt;

    /**
     * @var string
     */
    private $createdAt;

    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $emailVerifiedAt;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string
     */
    private $group;

    /**
     * @var string
     */
    private $availableWordsPrepaid;

    /**
     * @var string
     */
    private $availableImagesPrepaid;

    /**
     * @var string
     */
    private $availableCharsPrepaid;

    /**
     * @var string
     */
    private $availableMinutesPrepaid;

    /**
     * @var string
     */
    private $defaultVoiceoverLanguage;

    /**
     * @var string
     */
    private $defaultVoiceoverVoice;

    /**
     * @var string
     */
    private $jobRole;

    /**
     * @var string
     */
    private $referralId;

    /**
     * @var string
     */
    private $referredBy;

    /**
     * @var string
     */
    private $workbook;

    /**
     * @var int
     */
    private $workbookId;

    /**
     * @var int
     */
    private $workbookFolderId;

    /**
     * @var int
     */
    private $planId;

    /**
     * @var int
     */
    private $totalWords;

    /**
     * @var int
     */
    private $totalImages;

    /**
     * @var int
     */
    private $totalChars;

    /**
     * @var int
     */
    private $totalMinutes;

    /**
     * @var int
     */
    private $availableWords;

    /**
     * @var int
     */
    private $availableImages;

    /**
     * @var int
     */
    private $availableChars;

    /**
     * @var int
     */
    private $availableMinutes;

    /**
     * @var Role[]
     */
    private $roles;

    /**
     * @param string $name
     * @param string $email
     * @param string $country
     * @param string $updatedAt
     * @param string $createdAt
     * @param int $id
     * @param string $emailVerifiedAt
     * @param string $status
     * @param string $group
     * @param string $availableWordsPrepaid
     * @param string $availableImagesPrepaid
     * @param string $availableCharsPrepaid
     * @param string $availableMinutesPrepaid
     * @param string $defaultVoiceoverLanguage
     * @param string $defaultVoiceoverVoice
     * @param string $jobRole
     * @param string $referralId
     * @param string $referredBy
     * @param string $workbook
     * @param int $workbookId
     * @param int $workbookFolderId
     * @param int $planId
     * @param int $totalWords
     * @param int $totalImages
     * @param int $totalChars
     * @param int $totalMinutes
     * @param int $availableWords
     * @param int $availableImages
     * @param int $availableChars
     * @param int $availableMinutes
     * @param Role[] $roles
     */
    public function __construct(
        string $name,
        string $email,
        string $country,
        string $updatedAt,
        string $createdAt,
        int $id,
        string $emailVerifiedAt,
        string $status,
        string $group,
        string $availableWordsPrepaid,
        string $availableImagesPrepaid,
        string $availableCharsPrepaid,
        string $availableMinutesPrepaid,
        string $defaultVoiceoverLanguage,
        string $defaultVoiceoverVoice,
        string $jobRole,
        string $referralId,
        string $referredBy,
        string $workbook,
        int $workbookId,
        int $workbookFolderId,
        int $planId,
        int $totalWords,
        int $totalImages,
        int $totalChars,
        int $totalMinutes,
        int $availableWords,
        int $availableImages,
        int $availableChars,
        int $availableMinutes,
        array $roles
    ) {
        $this->name = $name;
        $this->email = $email;
        $this->country = $country;
        $this->updatedAt = $updatedAt;
        $this->createdAt = $createdAt;
        $this->id = $id;
        $this->emailVerifiedAt = $emailVerifiedAt;
        $this->status = $status;
        $this->group = $group;
        $this->availableWordsPrepaid = $availableWordsPrepaid;
        $this->availableImagesPrepaid = $availableImagesPrepaid;
        $this->availableCharsPrepaid = $availableCharsPrepaid;
        $this->availableMinutesPrepaid = $availableMinutesPrepaid;
        $this->defaultVoiceoverLanguage = $defaultVoiceoverLanguage;
        $this->defaultVoiceoverVoice = $defaultVoiceoverVoice;
        $this->jobRole = $jobRole;
        $this->referralId = $referralId;
        $this->referredBy = $referredBy;
        $this->workbook = $workbook;
        $this->workbookId = $workbookId;
        $this->workbookFolderId = $workbookFolderId;
        $this->planId = $planId;
        $this->totalWords = $totalWords;
        $this->totalImages = $totalImages;
        $this->totalChars = $totalChars;
        $this->totalMinutes = $totalMinutes;
        $this->availableWords = $availableWords;
        $this->availableImages = $availableImages;
        $this->availableChars = $availableChars;
        $this->availableMinutes = $availableMinutes;
        $this->roles = $roles;
    }

    /**
     * Returns Name.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @required
     * @maps name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Email.
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     *
     * @required
     * @maps email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Country.
     */
    public function getCountry(): string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     *
     * @required
     * @maps country
     */
    public function setCountry(string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Updated At.
     */
    public function getUpdatedAt(): string
    {
        return $this->updatedAt;
    }

    /**
     * Sets Updated At.
     *
     * @required
     * @maps updated_at
     */
    public function setUpdatedAt(string $updatedAt): void
    {
        $this->updatedAt = $updatedAt;
    }

    /**
     * Returns Created At.
     */
    public function getCreatedAt(): string
    {
        return $this->createdAt;
    }

    /**
     * Sets Created At.
     *
     * @required
     * @maps created_at
     */
    public function setCreatedAt(string $createdAt): void
    {
        $this->createdAt = $createdAt;
    }

    /**
     * Returns Id.
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @required
     * @maps id
     */
    public function setId(int $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Email Verified At.
     */
    public function getEmailVerifiedAt(): string
    {
        return $this->emailVerifiedAt;
    }

    /**
     * Sets Email Verified At.
     *
     * @required
     * @maps email_verified_at
     */
    public function setEmailVerifiedAt(string $emailVerifiedAt): void
    {
        $this->emailVerifiedAt = $emailVerifiedAt;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Group.
     */
    public function getGroup(): string
    {
        return $this->group;
    }

    /**
     * Sets Group.
     *
     * @required
     * @maps group
     */
    public function setGroup(string $group): void
    {
        $this->group = $group;
    }

    /**
     * Returns Available Words Prepaid.
     */
    public function getAvailableWordsPrepaid(): string
    {
        return $this->availableWordsPrepaid;
    }

    /**
     * Sets Available Words Prepaid.
     *
     * @required
     * @maps available_words_prepaid
     */
    public function setAvailableWordsPrepaid(string $availableWordsPrepaid): void
    {
        $this->availableWordsPrepaid = $availableWordsPrepaid;
    }

    /**
     * Returns Available Images Prepaid.
     */
    public function getAvailableImagesPrepaid(): string
    {
        return $this->availableImagesPrepaid;
    }

    /**
     * Sets Available Images Prepaid.
     *
     * @required
     * @maps available_images_prepaid
     */
    public function setAvailableImagesPrepaid(string $availableImagesPrepaid): void
    {
        $this->availableImagesPrepaid = $availableImagesPrepaid;
    }

    /**
     * Returns Available Chars Prepaid.
     */
    public function getAvailableCharsPrepaid(): string
    {
        return $this->availableCharsPrepaid;
    }

    /**
     * Sets Available Chars Prepaid.
     *
     * @required
     * @maps available_chars_prepaid
     */
    public function setAvailableCharsPrepaid(string $availableCharsPrepaid): void
    {
        $this->availableCharsPrepaid = $availableCharsPrepaid;
    }

    /**
     * Returns Available Minutes Prepaid.
     */
    public function getAvailableMinutesPrepaid(): string
    {
        return $this->availableMinutesPrepaid;
    }

    /**
     * Sets Available Minutes Prepaid.
     *
     * @required
     * @maps available_minutes_prepaid
     */
    public function setAvailableMinutesPrepaid(string $availableMinutesPrepaid): void
    {
        $this->availableMinutesPrepaid = $availableMinutesPrepaid;
    }

    /**
     * Returns Default Voiceover Language.
     */
    public function getDefaultVoiceoverLanguage(): string
    {
        return $this->defaultVoiceoverLanguage;
    }

    /**
     * Sets Default Voiceover Language.
     *
     * @required
     * @maps default_voiceover_language
     */
    public function setDefaultVoiceoverLanguage(string $defaultVoiceoverLanguage): void
    {
        $this->defaultVoiceoverLanguage = $defaultVoiceoverLanguage;
    }

    /**
     * Returns Default Voiceover Voice.
     */
    public function getDefaultVoiceoverVoice(): string
    {
        return $this->defaultVoiceoverVoice;
    }

    /**
     * Sets Default Voiceover Voice.
     *
     * @required
     * @maps default_voiceover_voice
     */
    public function setDefaultVoiceoverVoice(string $defaultVoiceoverVoice): void
    {
        $this->defaultVoiceoverVoice = $defaultVoiceoverVoice;
    }

    /**
     * Returns Job Role.
     */
    public function getJobRole(): string
    {
        return $this->jobRole;
    }

    /**
     * Sets Job Role.
     *
     * @required
     * @maps job_role
     */
    public function setJobRole(string $jobRole): void
    {
        $this->jobRole = $jobRole;
    }

    /**
     * Returns Referral Id.
     */
    public function getReferralId(): string
    {
        return $this->referralId;
    }

    /**
     * Sets Referral Id.
     *
     * @required
     * @maps referral_id
     */
    public function setReferralId(string $referralId): void
    {
        $this->referralId = $referralId;
    }

    /**
     * Returns Referred By.
     */
    public function getReferredBy(): string
    {
        return $this->referredBy;
    }

    /**
     * Sets Referred By.
     *
     * @required
     * @maps referred_by
     */
    public function setReferredBy(string $referredBy): void
    {
        $this->referredBy = $referredBy;
    }

    /**
     * Returns Workbook.
     */
    public function getWorkbook(): string
    {
        return $this->workbook;
    }

    /**
     * Sets Workbook.
     *
     * @required
     * @maps workbook
     */
    public function setWorkbook(string $workbook): void
    {
        $this->workbook = $workbook;
    }

    /**
     * Returns Workbook Id.
     */
    public function getWorkbookId(): int
    {
        return $this->workbookId;
    }

    /**
     * Sets Workbook Id.
     *
     * @required
     * @maps workbook_id
     */
    public function setWorkbookId(int $workbookId): void
    {
        $this->workbookId = $workbookId;
    }

    /**
     * Returns Workbook Folder Id.
     */
    public function getWorkbookFolderId(): int
    {
        return $this->workbookFolderId;
    }

    /**
     * Sets Workbook Folder Id.
     *
     * @required
     * @maps workbook_folder_id
     */
    public function setWorkbookFolderId(int $workbookFolderId): void
    {
        $this->workbookFolderId = $workbookFolderId;
    }

    /**
     * Returns Plan Id.
     */
    public function getPlanId(): int
    {
        return $this->planId;
    }

    /**
     * Sets Plan Id.
     *
     * @required
     * @maps plan_id
     */
    public function setPlanId(int $planId): void
    {
        $this->planId = $planId;
    }

    /**
     * Returns Total Words.
     */
    public function getTotalWords(): int
    {
        return $this->totalWords;
    }

    /**
     * Sets Total Words.
     *
     * @required
     * @maps total_words
     */
    public function setTotalWords(int $totalWords): void
    {
        $this->totalWords = $totalWords;
    }

    /**
     * Returns Total Images.
     */
    public function getTotalImages(): int
    {
        return $this->totalImages;
    }

    /**
     * Sets Total Images.
     *
     * @required
     * @maps total_images
     */
    public function setTotalImages(int $totalImages): void
    {
        $this->totalImages = $totalImages;
    }

    /**
     * Returns Total Chars.
     */
    public function getTotalChars(): int
    {
        return $this->totalChars;
    }

    /**
     * Sets Total Chars.
     *
     * @required
     * @maps total_chars
     */
    public function setTotalChars(int $totalChars): void
    {
        $this->totalChars = $totalChars;
    }

    /**
     * Returns Total Minutes.
     */
    public function getTotalMinutes(): int
    {
        return $this->totalMinutes;
    }

    /**
     * Sets Total Minutes.
     *
     * @required
     * @maps total_minutes
     */
    public function setTotalMinutes(int $totalMinutes): void
    {
        $this->totalMinutes = $totalMinutes;
    }

    /**
     * Returns Available Words.
     */
    public function getAvailableWords(): int
    {
        return $this->availableWords;
    }

    /**
     * Sets Available Words.
     *
     * @required
     * @maps available_words
     */
    public function setAvailableWords(int $availableWords): void
    {
        $this->availableWords = $availableWords;
    }

    /**
     * Returns Available Images.
     */
    public function getAvailableImages(): int
    {
        return $this->availableImages;
    }

    /**
     * Sets Available Images.
     *
     * @required
     * @maps available_images
     */
    public function setAvailableImages(int $availableImages): void
    {
        $this->availableImages = $availableImages;
    }

    /**
     * Returns Available Chars.
     */
    public function getAvailableChars(): int
    {
        return $this->availableChars;
    }

    /**
     * Sets Available Chars.
     *
     * @required
     * @maps available_chars
     */
    public function setAvailableChars(int $availableChars): void
    {
        $this->availableChars = $availableChars;
    }

    /**
     * Returns Available Minutes.
     */
    public function getAvailableMinutes(): int
    {
        return $this->availableMinutes;
    }

    /**
     * Sets Available Minutes.
     *
     * @required
     * @maps available_minutes
     */
    public function setAvailableMinutes(int $availableMinutes): void
    {
        $this->availableMinutes = $availableMinutes;
    }

    /**
     * Returns Roles.
     *
     * @return Role[]
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    /**
     * Sets Roles.
     *
     * @required
     * @maps roles
     *
     * @param Role[] $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['name']                       = $this->name;
        $json['email']                      = $this->email;
        $json['country']                    = $this->country;
        $json['updated_at']                 = $this->updatedAt;
        $json['created_at']                 = $this->createdAt;
        $json['id']                         = $this->id;
        $json['email_verified_at']          = $this->emailVerifiedAt;
        $json['status']                     = $this->status;
        $json['group']                      = $this->group;
        $json['available_words_prepaid']    = $this->availableWordsPrepaid;
        $json['available_images_prepaid']   = $this->availableImagesPrepaid;
        $json['available_chars_prepaid']    = $this->availableCharsPrepaid;
        $json['available_minutes_prepaid']  = $this->availableMinutesPrepaid;
        $json['default_voiceover_language'] = $this->defaultVoiceoverLanguage;
        $json['default_voiceover_voice']    = $this->defaultVoiceoverVoice;
        $json['job_role']                   = $this->jobRole;
        $json['referral_id']                = $this->referralId;
        $json['referred_by']                = $this->referredBy;
        $json['workbook']                   = $this->workbook;
        $json['workbook_id']                = $this->workbookId;
        $json['workbook_folder_id']         = $this->workbookFolderId;
        $json['plan_id']                    = $this->planId;
        $json['total_words']                = $this->totalWords;
        $json['total_images']               = $this->totalImages;
        $json['total_chars']                = $this->totalChars;
        $json['total_minutes']              = $this->totalMinutes;
        $json['available_words']            = $this->availableWords;
        $json['available_images']           = $this->availableImages;
        $json['available_chars']            = $this->availableChars;
        $json['available_minutes']          = $this->availableMinutes;
        $json['roles']                      = $this->roles;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
